version: '3.8'

services:
  finansmart-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finansmart-app
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DatabaseConnection=${DATABASE_CONNECTION_STRING}
    networks:
      - finansmart-network
    restart: unless-stopped

  # Oracle Database (opcional - descomente se necessário)
  # oracle-db:
  #   image: container-registry.oracle.com/database/express:21.3.0-xe
  #   container_name: finansmart-oracle-db
  #   ports:
  #     - "1521:1521"
  #     - "5500:5500"
  #   environment:
  #     - ORACLE_PWD=${ORACLE_PASSWORD:-OraclePassword123}
  #     - ORACLE_CHARACTERSET=AL32UTF8
  #   volumes:
  #     - oracle-data:/opt/oracle/oradata
  #   networks:
  #     - finansmart-network
  #   restart: unless-stopped

networks:
  finansmart-network:
    driver: bridge

volumes:
  oracle-data:
    driver: local
