version: '3.8'

# Docker Compose para DESENVOLVIMENTO
# Uso: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  finansmart-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - .:/app
      - /app/bin
      - /app/obj
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER=1
    command: dotnet watch run --no-launch-profile

  oracle-db:
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=DevPassword123

  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
