name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main
      - master
      - feature/*
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: finansmart-app
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Display repository structure
      run: |
        echo "=== Repository Root ==="
        pwd
        ls -la
        echo ""
        echo "=== Looking for .csproj and .sln files ==="
        find . -name "*.csproj" -o -name "*.sln" | head -20
        
    - name: Restore dependencies
      run: dotnet restore Finansmart.csproj
      working-directory: ./
      
    - name: Build project
      run: dotnet build Finansmart.csproj --configuration Release --no-restore
      working-directory: ./
      
    - name: Run tests (if available)
      run: |
        if [ -f "../Finansmart.Tests/Finansmart.Tests.csproj" ]; then
          echo "Running tests..."
          dotnet test ../Finansmart.Tests/Finansmart.Tests.csproj --configuration Release --verbosity normal
        else
          echo "No test project found at ../Finansmart.Tests/, skipping tests"
        fi
      working-directory: ./
      continue-on-error: true
      
    - name: Publish application
      run: dotnet publish Finansmart.csproj -c Release -o ${{ github.workspace }}/${{ env.AZURE_WEBAPP_PACKAGE_PATH }} --no-build
      working-directory: ./
      
    - name: Verify publish output
      run: |
        echo "=== Published files ==="
        ls -la ${{ github.workspace }}/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
