name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main
      - master
      - feature/*  # Adicionada verificação para branches de recursos
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: finansmart-app
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: List directory structure
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
        echo "Looking for .sln files:"
        find . -name "*.sln" -o -name "*.csproj" | head -20
        
    - name: Restore dependencies
      run: |
        if [ -f "Finansmart.sln" ]; then
          dotnet restore Finansmart.sln
        else
          dotnet restore Finansmart.csproj
        fi
      
    - name: Build
      run: |
        if [ -f "Finansmart.sln" ]; then
          dotnet build Finansmart.sln --configuration Release --no-restore
        else
          dotnet build Finansmart.csproj --configuration Release --no-restore
        fi
      
    - name: Run tests
      run: |
        if [ -d "../Finansmart.Tests" ]; then
          dotnet test ../Finansmart.Tests/Finansmart.Tests.csproj --configuration Release --no-build --verbosity normal
        else
          echo "Tests project not found, skipping tests..."
        fi
      continue-on-error: true
      
    - name: Publish
      run: dotnet publish Finansmart.csproj -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} --no-build
      
    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
